## Following does not work. Gives error Query requires iterating over all vertices. For better performance, use indexes
titan-db:
  config:
    location: file:src/main/resources/dev/titan-berkeleydb.properties

schema:
  labels:
    - email
    - person
  properties:
    - 
      dataType: String
      name: i_uri
    - 
      dataType: String
      name : name
  propertyIndexes:
    -
      name: i_uri_index
      propertyKeys:
        - i_uri
        